version: '2'

services:
  drupal:
    image: drupal
    ports: 
      - "8080:80"
    volumes:
      - modules:/var/www/html/modules
      - profiles:/var/www/html/profiles
      - themes:/var/www/html/themes
      - sites:/var/www/html/sites
  postgres:
    image:  postgres
    environment: 
      POSTGRES_PASSWORD: mypass

volumes:
  modules:
  profiles:
  themes:
  sites:

